### ISSUE TITLE
Inject Encoder for kafka producer

### ISSUE THREAD

**Issue by drakos74** [beatlabs/patron#111]
## Is your feature request related to a problem? Please describe

- complimentary issue to #100 

- When interacting with kafka the encoding options are currently hardcoded to be either json or protobuf.
- In the general case , where somebody wants to implement some custom (potentially fast serialization protocol) or use other industry standards (i.e. avro) the framework does not support that out of the box.

## Describe the solution

- inject an encoder implementation tied to the kafka producer
- if no encoder is provided fall back to the current approach as a default
- keep backwards compatibility

## Additional context

- solution should be following same logic and assumptions as in #100 
These 2 issues are complimentary to each other.

**Comment by tpaschalis** [comment]
I could pick this up if there's no objection. Having #100 and [your PR](https://github.com/taxibeat/crom/pull/74) as a guideline will help. I might ask for some help write meaningful testcases and any Kafka-specific issues that may arise.

**Comment by tpaschalis** [comment]
I could pick this up if there's no objection. Having #100 and [your PR](https://github.com/beatlabs/patron/pull/101) as a guideline will help. I might ask for some help regarding writing meaningful testcases and any Kafka-specific issues that may arise.

**Comment by mantzas** [comment]
@tpaschalis if @drakos74 has no issue with it then move on. He has actually more knowledge on this since he works by using avro/protobuf in kafka...

**Comment by drakos74** [comment]
@tpaschalis , yes. Thank you for the initiative! Please go for it 👍 If there is anything i can help, just let me know!

**Comment by tpaschalis** [comment]
Hey, I've started working on the issue, but I'm not 100% sure I'm on the right track...

My first goal is to    
a) add a new encoder field on the `AsyncProducer` struct  
b) use that to generalize the encoding function that is present in `createProducerMessage()`.     
Right now it's always a `sarama.ByteEncoder` (eg. [here](https://github.com/beatlabs/patron/blob/07888c36b9ac491264a41bd4c9b1bea73c88230b/trace/kafka/kafka.go#L140)), but it could be a `ProtobufEncoder`,  a `JSONEncoder`, or an `AvroEncoder` later on.
c) add the necessary headers to the newly-encoded message

Am I missing anything, does this sound dumb? I'll be opening a draft PR sooner or later so we can discuss on actual code.

**Comment by mantzas** [comment]
@tpaschalis there is already a package that handles encoding in our codebase called "encoding"... you should us it to generalize the encoding part...

**Comment by tpaschalis** [comment]
Hey everyone! I opened a Draft PR so we can discuss on actual code.   

After a discussion with @drakos74, I changed the injected field to an `encoding.EncodeFunc`, and set up a default along with the Content-Type headers.

After a discussion with @moukoublen, I'd like your input on whether we're on the right path.  
Right now, our abstraction of a Kafka Message contains an [already-serialized `[]byte` body](https://github.com/beatlabs/patron/blob/07888c36b9ac491264a41bd4c9b1bea73c88230b/trace/kafka/kafka.go#L18).      
The Send method of patron's AsyncProducer works with such messages; the serialization happens on the client side, and not in the producer. 

We discussed about a couple of options
- Creating a new SerializeAndSend function that receives an `interface{}`, serializes it using the encoder and calls the already-existing Send()
```
func (ap *AsyncProducer) SerializeAndSend(ctx context.Context, obj interface{}, topic string, key *string) error
```
- Generalizing the `Message` abstraction, to have an ` interface{}` as a body, which will be 
    + either serialized with the injected function, 
    + or a default, pass-through encoder, which will try to cast to `[]byte` or `string`, similar to the `sarama.ByteEncoder` and `sarama.StringEncoder`

What do you all think?

**Comment by mantzas** [comment]
> Hey everyone! I opened a Draft PR so we can discuss on actual code.
> 
> After a discussion with @drakos74, I changed the injected field to an `encoding.EncodeFunc`, and set up a default along with the Content-Type headers.
> 
> After a discussion with @moukoublen, I'd like your input on whether we're on the right path.
> Right now, our abstraction of a Kafka Message contains an [already-serialized `[]byte` body](https://github.com/beatlabs/patron/blob/07888c36b9ac491264a41bd4c9b1bea73c88230b/trace/kafka/kafka.go#L18).
> The Send method of patron's AsyncProducer works with such messages; the serialization happens on the client side, and not in the producer.
> 
> We discussed about a couple of options
> 
>     * Creating a new SerializeAndSend function that receives an `interface{}`, serializes it using the encoder and calls the already-existing Send()
> 
> 
> ```
> func (ap *AsyncProducer) SerializeAndSend(ctx context.Context, obj interface{}, topic string, key *string) error
> ```
> 
>     * Generalizing the `Message` abstraction, to have an ` interface{}` as a body, which will be
>       
>       * either serialized with the injected function,
>       * or a default, pass-through encoder, which will try to cast to `[]byte` or `string`, similar to the `sarama.ByteEncoder` and `sarama.StringEncoder`
> 
> 
> What do you all think?

The current implementation of the producer has been kept encoding agnostic in order to make it simpler. The user has to decide how to encode...
If we inject the encoder, the API can then accept and `interface{}` and do the encoding inside. I would use `SendRaw([]byte)` and `Send(interface{})` to distinguish between the two.
There is now the issue with the Header... If we want to be really correct about it we should send the appropriate header each time.
This means that SendRaw needs this as an argument and Send should be provided when creating the producer.
Another thing that I would suggest: The producer constructor should accept the encoder optionally which means if it is not provided we should setup it up to use JSON as default.
Makes sense?

**Comment by tpaschalis** [comment]
Yes, I think your points make sense.  
I've attempted to implement these changes, as well as write some testcases. I'll be more than happy to hear feedback, and see where we can improve!
