### ISSUE TITLE
Sql Client tracing does not populate the db name and the user

### ISSUE THREAD

**Issue by mantzas** [beatlabs/patron#112]
## Is your feature request related to a problem? Please describe

When opening a DB we do not populate the user and db name.
We should get from the DSN the username and the db name and create the proper DB.
Check out sql.go line 114 and 123.

## Is this a bug? Please provide steps to reproduce, a failing test etc.

Just use the traced sql client.

## Describe the solution

Extract the user and db name.

**Comment by tpaschalis** [comment]
I could pick this up if there's no objection.

Should we be able to just parse DSNs in the form of `username:password@protocol(address)/dbname?param=value` or    
ODBC-style `SERVER=localhost;DATABASE=<mydb>;USER=<myuser>;PASSWORD=<mypass>;` as well?

The parsed result should just populate the `connInfo` field of the `DB` struct, right?
