### ISSUE TITLE
Replace errors.Wrap with fmt.Errorf from go 1.13

### ISSUE THREAD

**Issue by mantzas** [beatlabs/patron#124]
## Is your feature request related to a problem? Please describe

Go has introduced error wrapping with `fmt.Errorf`. We should remove the wrap methods from the errors package.

**Comment by fpapadopou** [comment]
More details about Go's error wrapping can be found [here](https://blog.golang.org/go1.13-errors)

**Comment by mantzas** [comment]
@fpapadopou PR already waiting for your review...
