### ISSUE TITLE
Introduce a generic cache package

### ISSUE THREAD

**Issue by mantzas** [beatlabs/patron#127]
## Is your feature request related to a problem? Please describe

There is a need to introduce a generic cache package which can be used either directly or as part of the caching mechanism provided by HTTP or gRPC server.

## Describe the solution

The cache package would contain at its root folder a simple interface like:

```
type Cache interface {
	Get(key string) (interface{}, bool, error)
	Set(key string, value interface{})
        SetTTL(key string, ttl time.Duration, value interface{})
}
```

and subpackage could contain concrete implementations of this cache e.g. LRU, Redis backed etc.

## Additional context

for the beginning we should support the follwoing 2 options, one memory based and one witha backing store:
- LRU, using the package github.com/hashicorp/golang-lru
- Redis based, using the most known package for this e.g. github.com/go-redis/redis/v7

**Comment by tpaschalis** [comment]
Hey Sotiris. If it's okay with you, I'd like to pick this up; I feel that implementing something new while trying to follow best practices and the rest of the project conventions will allow me to understand Patron better.
