### ISSUE TITLE
Introduce HTTP server side caching

### ISSUE THREAD

**Issue by mantzas** [beatlabs/patron#128]
## Is your feature request related to a problem? Please describe

We would like to introduce optional caching on the server-side in order to improve performance and the load on our systems.
The solution should comply with the [RFC](https://www.ietf.org/rfc/rfc2616.txt) and should meet the below requirements:

- Optional caching per route (and obviously only HTTP GET)
- Use the generic cache interface introduced with #127 
- Wait for the completion of #115  which introduces a builder patter for the HTTP component

## Describe the solution

- Use the builder pattern to setup the cache
- Add the caching per route
- Follow the RFC for the headers

**Comment by drakos74** [comment]
i would be interested in working on this, connected to that one : https://github.com/beatlabs/patron/issues/129. If there are no objections...

**Comment by drakos74** [comment]
just for consistency , RFC for headers :  https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control

**Comment by drakos74** [comment]
The initial idea is to create a caching middleware. Does that sound reasonable ?

**Comment by drakos74** [comment]
On it!
It seems though that this one would help a lot with the abstraction ... https://github.com/beatlabs/patron/pull/167 . Does it make sense if i base my changes on it ? And we can always release them one by one , when the 167 gets merged.

**Comment by mantzas** [comment]
@drakos74 I am actually already finished with #167, so just CR and merge and you have everything you need.
