### ISSUE TITLE
Kafka Producer Builder Pattern

### ISSUE THREAD

**Issue by tpaschalis** [beatlabs/patron#130]
## Is your feature request related to a problem? Please describe

The Kafka Producer doesn't need as much configuration as the Consumer side, but it would be helpful to standardize its creation by using a builder, à la #54 [Async Component Builder Pattern](https://github.com/beatlabs/patron/issues/54).

## Describe the solution

Use the builder pattern to facilitate the creation of trace producers as
```go
prd, err := kafka.NewAsyncProducer().WithBrokers().WithVersion().WithTimeouts().WithRequiredAcksPolicy().WithEncoder()
```

Ideally, we should revisit [sarama's configuration](https://github.com/Shopify/sarama/blob/master/config.go) in case we would like to set up some new properties.

**Comment by tpaschalis** [comment]
Thanks to @drakos74 for the suggestion.     
Since I've implemented the pattern [on another occasion](https://github.com/beatlabs/patron/issues/53), and I'm currently working on the Kafka Producer, I could pick this up as well, if there's no objection @mantzas

**Comment by mantzas** [comment]
@tpaschalis no objection at all, go for it...
