### ISSUE TITLE
Update tracing and metrics version to latest

### ISSUE THREAD

**Issue by drakos74** [beatlabs/patron#139]
## Is your feature request related to a problem? Please describe

Keep up with dependencies versions towards our v1 release.
e.g. make sure that for v1 all dependencies are up to date

## Describe the solution

Update version of tracing and metric and fix any regression issues

**Comment by mantzas** [comment]
Since jaeger distributed tracing is using prometheus also we should look into upgrading that one in order to update prometheus as well...

**Comment by tpaschalis** [comment]
I could start looking into upgrading the Jaeger/Prometheus pair and fixing any issues that arise.
