### ISSUE TITLE
Introduce kafka operational metrics

### ISSUE THREAD

**Issue by drakos74** [beatlabs/patron#140]
#136  Is your feature request related to a problem? Please describe

Patron provides by default prometheus metrics for different components, either directly or through it's dependencies.
For kafka processing, there are no metrics out-of-the-box from sarama (except for the consumer lag).
We should consider introducing processing metrics to facilitate the usage of kafka consumer / producer clients in patron.

## Describe the solution

Add (via prometheus) metrics for 

- consumer 
-- number of messages received
-- number of messages decoded (or decoding errors)
-- ack count
-- nack count

- producer
-- number of messages sent
-- number of message encoding errors (or messages encoded)
-- ack count
-- nack count

## Additional context

Whatever other metrics would make sense within the scope of tracking kafka operation / performance

**Comment by tpaschalis** [comment]
I'd like to pick this one up; it's an opportunity to see more about prometheus logging 😃 
Should this logging be always-enabled, or there should be a flag that enables/disables it when creating the producer and consumer?

**Comment by mantzas** [comment]
@tpaschalis Hi, Prometheus does not work like logging. Pls take a look first in the official documentation before starting this one. Secondly, I like your enthusiasm, but you have already 2 open PR running. We should close some of them first before starting a new one.

**Comment by tpaschalis** [comment]
Thanks, I'll take a deeper dive in the Prometheus docs, and explore how it works in Patron and other projects. 

Once we merge some of the other PRs, and if no one has picked this up, I'll be happy to help! :)
