### ISSUE TITLE
Kafka consumer group processing issue

### ISSUE THREAD

**Issue by mantzas** [beatlabs/patron#146]
## Is your feature request related to a problem? Please describe

When using consumer groups we want to move to the next message only if the current one is succesfully processed.
At this point we do not guarantee this because we:
- Get a message from Kafka and try to put in on a unbuffered channel
- After the processor get's this message we do not wait for the message to be aknowledged and pull the next one.

check out `ConsumeClaim` in group.go...

We should wait for the message to be succesfully processed in order to get the next one.

## Is this a bug? Please provide steps to reproduce, a failing test etc.

We have to create a test to show this happening in order to fix it.

## Describe the solution

Let's read on Kafka consumer group aknowledgments and see how to do this...
An we should also see if the buffered channel option makes sense since we want to acknowldge every message before moving to the next one.

**Comment by drakos74** [comment]
Should this be under an option property ? Maybe for some cases, clients might not want to wait for it, but process quickly whatever they can ...

**Comment by mantzas** [comment]
@drakos74 no, when using consumer groups you want actually confirm the message to be processed before getting the next one.
Kafka is not a message broker where you can reprocess a message... no DLQ etc....
as soon as you acknowledge the message the iterator has moved forward and the message cannot be processed anymore except if you reprocess based on a specific iterator position.

**Comment by mantzas** [comment]
After an investigation, there is actually not a bug since we have acknowledged a message in order to be committed in Kafka with `session.MarkMessage()`.
The flow is the following with the unbuffered channel:
As soon as a message has been processed from the channel a new one will try to be added to the channel but will be blocked until the processing function picks it up.
