### ISSUE TITLE
Extend sarama.AsyncProducer to allow its correct use

### ISSUE THREAD

**Issue by gm42** [beatlabs/patron#148]
## Is your feature request related to a problem? Please describe

It is currently not possible to use the `sarama.AsyncProducer` correctly because the method `AsyncClose()` is not exposed or proxied.

## Is this a bug? Please provide steps to reproduce, a failing test etc.

See sarama GoDoc for how to properly use the AsyncProducer and spool for all asynchronous operations before exiting a Go process: https://godoc.org/github.com/Shopify/sarama#AsyncProducer

## Describe the solution

The solution I propose is to use a more Go-idiomatic approach than "sealing off" the `sarama.AsyncProducer` in a private field: extending the object so that the developer is responsible for properly using it.

## Additional context

Please see related PR for the approach I had in mind; forgive me for such an invasive first contribution, all feedback welcome.

**Comment by mantzas** [comment]
@gm42 hi, thanks for the issue. Could you point me to the documentation embedding is idiomatic go and "sealing off" is not? I think I have missed that.

**Comment by gm42** [comment]
@mantzas I would prefer we look at the PR from the perspective of fixing the mentioned issue (to not go too much off-topic); the issue here is not about Go style but about using the `sarama.AsyncProducer` correctly (so if you can think of a better way to solve it which does not involve the proposed solution, embedding, we can pursue that approach instead), but sure: https://golang.org/doc/effective_go.html#embedding

The way I read it and interpret it is that it is absolutely fine to do what is being done here (create a private field instead of embedding), but if one were to consistently create forwarding methods then it's better to use embedding.

A relevant quote from the Effective Go documentation mentioned above:
> The embedded elements are pointers to structs and of course must be initialised to point to valid structs before they can be used. [...] but then to promote the methods of the fields and to satisfy the io interfaces, we would also need to provide forwarding methods [...] By embedding the structs directly, we avoid this bookkeeping. The methods of embedded types come along for free

**Comment by mantzas** [comment]
@gm42 I was curious about it being the idiomatic way to Go as you mentioned it. You can, of course, do this also but then you are exposing all the internals which in some cases is perfectly valid but in others, you want to have control over what is being set or not. Both approaches are perfectly fine and I agree with both of them, but embedding does not mean idiomatic, it is just another option. Here we chose to hide the internals and every time we need to expose something we just implement it. This happens thankfully rarely. 

In this particular case, we wanted to inject our distributed tracing mechanism into the producer. Embedding the producer now provides more ways to send messages to Kafka so it gives the developer the option to bypass the tracing part. In this particular case, embedding is the wrong way to go I am afraid...

**Comment by gm42** [comment]
> This happens thankfully rarely.

@mantzas in future I will open another issue/make another PR for the support of `Successes()`; for this specific issue I think we can already use `Close()` to correctly wait for all messages to be flushed.
