### ISSUE TITLE
Introduce component and client packages

### ISSUE THREAD

**Issue by mantzas** [beatlabs/patron#150]
## Is your feature request related to a problem? Please describe

The organization of the package do not make sense anymore since the introduction of gRPC which is sync and async at the same time.

## Describe the solution

We should introduce the following packages instead of sync and async:

- component
-- HTTP
-- gRPC
-- async
--- kafka
--- amqp
--- sqs

- client
-- amqp
-- es
-- etc.

## Additional context

the HTTP package is now self-contained and doesn't need the sync as a separate package.

**Comment by gm42** [comment]
Two wishes for this refactor/rework:
* more flexibility in the status code while still keeping some sanity checks/implicit behavior, see #160
* support for GET requests with body (there is no separate issue for this but we can have it if needed; from recent research what I found out is that legacy applications do not support it always/well but the HTTP standard has been amended to explicitly say that it's not forbidden; ElasticSearch is one famous example "in the wild" of these semantics; Go has no opinion on this as well and supports it without problems).

**Comment by mantzas** [comment]
@gm42 maybe we should move it to the other ticket #160 in order to simplify a lot of things there.
This ticket is just about moving the old packages into the a better package structure with minimal change on functionality.
