### ISSUE TITLE
Add integration tests for async/amqp

### ISSUE THREAD

**Issue by tpaschalis** [beatlabs/patron#171]
## Is your feature request related to a problem? Please describe

Right now, and due to recent commits, the project's code coverage is below 80%. 

This means that upcoming PRs are blocked (such as #159). 

The two main packages that lack in coverage are `trace/sql` and `async/amqp`. I think that separate PRs should be opened to improve coverage, instead of shoehorning unrelated testcases just to raise that percentage.

## Is this a bug? Please provide steps to reproduce, a failing test etc.

Not a bug, but we just started measuring the coverage, and the issue was revealed.

[This](https://github.com/beatlabs/patron/pull/159#issuecomment-595721836) is the report, which blocks the PR, even though it has 100% coverage on new code.

## Describe the solution
- Modify Github Actions definition so that it starts the `rabbitmq` container and network.
- Add integration tests for the `async/amqp` package.

## Additional context
My main concern when starting to add such tests is their **flakiness**. 

We need to ensure that these integration tests can run easily and pass consistently every time. Right now, we *do* have some flakiness in async/kafka, but we should strive to fix it soon and be careful to not include even more.

**Comment by mantzas** [comment]
v1 will be deprecated so there is no reason to keep this
