### ISSUE TITLE
Add broker/topics validation for kafra/group.New

### ISSUE THREAD

**Issue by superstas** [beatlabs/patron#174]
Hi there,

## Is your feature request related to a problem? Please describe
We've found out the since the last release `topic` became a `[]string{}` instead of a `string`.

There was a [validation](https://github.com/beatlabs/patron/blob/v0.29.0/async/kafka/kafka.go#L94) for emptiness of `topic` argument.

Since the latest release `topics` argument is being validated only for slice emptiness but not values.

It led us to a few broken tests.
It would be nice to have values validation ( `if value != ""` ) as well.

## Is this a bug? Please provide steps to reproduce, a failing test etc.

I think so, it depends on what Patron validates by default.

### Involved parts
- `group` package: validation of `brokers` and `topics`
- `simple` package: validation of `brokers`

### Questions
- What do you think about it? Is it a bug? Should Patron validate ( in a simple way ) these values?
- Do we have any other places that should be validated in the same manner?

Thank you.

**Comment by drakos74** [comment]
Hi @superstas ! Thanks for pointing that out and raising the issue.
Would you be interested to pick this up maybe, and add a fix ?

**Comment by superstas** [comment]
Hi @drakos74 , thank you for the answer.

Yes, I'll pick it up and send PR.
