### ISSUE TITLE
Go 1.14.1 breaks profiling tests

### ISSUE THREAD

**Issue by mantzas** [beatlabs/patron#189]
## Is your feature request related to a problem? Please describe

After upgrading to Go 1.14.1 the test `patron/component/http/profiling_test.go:47` breaks with the following panic.

`2020/03/22 10:35:54 http: panic serving 127.0.0.1:46438: runtime error: index out of range [-1]
goroutine 145 [running]:
net/http.(*conn).serve.func1(0xc0002763c0)
	/usr/local/go/src/net/http/server.go:1772 +0x147
panic(0xc07c80, 0xc000536440)
	/usr/local/go/src/runtime/panic.go:973 +0x3e3
runtime/pprof.runtime_expandFinalInlineFrame(0xc00036e000, 0x0, 0x20, 0x0, 0x0, 0x0)
	/usr/local/go/src/runtime/symtab.go:156 +0x3aa
runtime/pprof.(*profileBuilder).appendLocsForStack(0xc0000ff080, 0x0, 0x0, 0x0, 0xc00036e000, 0x0, 0x20, 0x2, 0xc00, 0x7f86ecf2da00)
	/usr/local/go/src/runtime/pprof/proto.go:389 +0x10c
runtime/pprof.printCountProfile(0xd29240, 0xc0002421c0, 0x0, 0xc4eb40, 0xc, 0xd2e8c0, 0xc0000d8320, 0x181800c00029e410, 0x30)
	/usr/local/go/src/runtime/pprof/pprof.go:449 +0xbfc
runtime/pprof.writeRuntimeProfile(0xd29240, 0xc0002421c0, 0x0, 0xc4eb40, 0xc, 0xc72758, 0x43498f, 0xc0003f40ff)
	/usr/local/go/src/runtime/pprof/pprof.go:702 +0x12d
runtime/pprof.writeThreadCreate(0xd29240, 0xc0002421c0, 0x0, 0xc0003f40ff, 0xc0003f4000)
	/usr/local/go/src/runtime/pprof/pprof.go:643 +0x72
runtime/pprof.(*Profile).WriteTo(0x1155fc0, 0xd29240, 0xc0002421c0, 0x0, 0xc0002421c0, 0xc0000c01b0)
	/usr/local/go/src/runtime/pprof/pprof.go:329 +0x4fc
net/http/pprof.handler.ServeHTTP(0xc4eb40, 0xc, 0xd32520, 0xc0002421c0, 0xc00029e400)
	/usr/local/go/src/net/http/pprof/pprof.go:248 +0x3b4
github.com/beatlabs/patron/component/http.profThreadcreate(0xd32520, 0xc0002421c0, 0xc00029e400)
	/home/mantzas/src/go/beat/patron/component/http/profiling.go:61 +0x99
net/http.HandlerFunc.ServeHTTP(0xc716b8, 0xd32520, 0xc0002421c0, 0xc00029e400)
	/usr/local/go/src/net/http/server.go:2012 +0x52
net/http.(*ServeMux).ServeHTTP(0xc000020780, 0xd32520, 0xc0002421c0, 0xc00029e400)
	/usr/local/go/src/net/http/server.go:2387 +0x289
net/http.serverHandler.ServeHTTP(0xc0001bc0e0, 0xd32520, 0xc0002421c0, 0xc00029e400)
	/usr/local/go/src/net/http/server.go:2807 +0xcf
net/http.(*conn).serve(0xc0002763c0, 0xd33b60, 0xc0000201c0)
	/usr/local/go/src/net/http/server.go:1895 +0x838
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2933 +0x5b7
2020/03/22 10:35:54 http: panic serving 127.0.0.1:46440: runtime error: index out of range [-1]
goroutine 258 [running]:
net/http.(*conn).serve.func1(0xc000194000)
	/usr/local/go/src/net/http/server.go:1772 +0x147
panic(0xc07c80, 0xc0002a4360)
	/usr/local/go/src/runtime/panic.go:973 +0x3e3
runtime/pprof.runtime_expandFinalInlineFrame(0xc0002e2000, 0x0, 0x20, 0x0, 0x0, 0x0)
	/usr/local/go/src/runtime/symtab.go:156 +0x3aa
runtime/pprof.(*profileBuilder).appendLocsForStack(0xc0003809a0, 0x0, 0x0, 0x0, 0xc0002e2000, 0x0, 0x20, 0x2, 0xc00, 0x7f86ecf29400)
	/usr/local/go/src/runtime/pprof/proto.go:389 +0x10c
runtime/pprof.printCountProfile(0xd29240, 0xc0001bc1c0, 0x0, 0xc4eb40, 0xc, 0xd2e8c0, 0xc00000e0c0, 0x181800c000192710, 0x30)
	/usr/local/go/src/runtime/pprof/pprof.go:449 +0xbfc
runtime/pprof.writeRuntimeProfile(0xd29240, 0xc0001bc1c0, 0x0, 0xc4eb40, 0xc, 0xc72758, 0x43498f, 0xc0003f41ff)
	/usr/local/go/src/runtime/pprof/pprof.go:702 +0x12d
runtime/pprof.writeThreadCreate(0xd29240, 0xc0001bc1c0, 0x0, 0xc0003f41ff, 0xc0003f4000)
	/usr/local/go/src/runtime/pprof/pprof.go:643 +0x72
runtime/pprof.(*Profile).WriteTo(0x1155fc0, 0xd29240, 0xc0001bc1c0, 0x0, 0xc0001bc1c0, 0xc000026420)
	/usr/local/go/src/runtime/pprof/pprof.go:329 +0x4fc
net/http/pprof.handler.ServeHTTP(0xc4eb40, 0xc, 0xd32520, 0xc0001bc1c0, 0xc000192700)
	/usr/local/go/src/net/http/pprof/pprof.go:248 +0x3b4
github.com/beatlabs/patron/component/http.profThreadcreate(0xd32520, 0xc0001bc1c0, 0xc000192700)
	/home/mantzas/src/go/beat/patron/component/http/profiling.go:61 +0x99
net/http.HandlerFunc.ServeHTTP(0xc716b8, 0xd32520, 0xc0001bc1c0, 0xc000192700)
	/usr/local/go/src/net/http/server.go:2012 +0x52
net/http.(*ServeMux).ServeHTTP(0xc000020780, 0xd32520, 0xc0001bc1c0, 0xc000192700)
	/usr/local/go/src/net/http/server.go:2387 +0x289
net/http.serverHandler.ServeHTTP(0xc0001bc0e0, 0xd32520, 0xc0001bc1c0, 0xc000192700)
	/usr/local/go/src/net/http/server.go:2807 +0xcf
net/http.(*conn).serve(0xc000194000, 0xd33b60, 0xc000020440)
	/usr/local/go/src/net/http/server.go:1895 +0x838
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2933 +0x5b7
--- FAIL: Test_PprofHandlers (1.18s)
    --- FAIL: Test_PprofHandlers/threadcreate (0.01s)
        profiling_test.go:46: 
            	Error Trace:	profiling_test.go:46
            	Error:      	Received unexpected error:
            	            	Get "http://127.0.0.1:35381/debug/pprof/threadcreate/": EOF
            	Test:       	Test_PprofHandlers/threadcreate
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb32f90]

goroutine 226 [running]:
testing.tRunner.func1.1(0xbb06e0, 0x1153030)
	/usr/local/go/src/testing/testing.go:941 +0x5d0
testing.tRunner.func1(0xc0000f2360)
	/usr/local/go/src/testing/testing.go:944 +0x600
panic(0xbb06e0, 0x1153030)
	/usr/local/go/src/runtime/panic.go:973 +0x3e3
github.com/beatlabs/patron/component/http.Test_PprofHandlers.func1(0xc0000f2360)
	/home/mantzas/src/go/beat/patron/component/http/profiling_test.go:47 +0x200
testing.tRunner(0xc0000f2360, 0xc0000d8260)
	/usr/local/go/src/testing/testing.go:992 +0x1ec
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1043 +0x661`

## Is this a bug? Please provide steps to reproduce, a failing test etc.

It seems to be a bug because the only thing that patron does is to route the request to the underlying pprof handler.

**Comment by tpaschalis** [comment]
The issue has to do with the way the profiler handles an empty stack trace

Looking at the `golang/go` repo, it was [reported](https://github.com/golang/go/issues/37967) and [resolved](https://go-review.googlesource.com/c/go/+/224458/) a couple of days ago, and is going to be cherry-picked into the next minor release.

I *did* try to cherry-pick the relevant commit `5bc75a3097a3671055f0f9c503850edbe830601d`, and [re-built](https://golang.org/doc/contribute.html#quick_test) the Go binary which includes this fix. I can confirm that it works.

```bash
$ # Go 1.14.1
$ go test ./sync/http
runtime: pcdata is -2 and 4 locals stack map entries for runtime/pprof.runtime_expandFinalInlineFrame (targetpc=0x1053039)
fatal error: bad symbol table

runtime stack:
runtime.throw(0x159c4f2, 0x10)
...
...
$
$ # Go 1.14.1 with this specific commit
$ Users/paschalistsilias/Workspace/Git/go/bin/go test ./sync/http
ok  	github.com/beatlabs/patron/sync/http	1.356s
```

So for now, we can keep working with 1.13 until the next minor release, but if you absolutely must work with 1.14.1, there's how.

**Comment by mantzas** [comment]
Seems to be fixed now
