### ISSUE TITLE
Introduce Kafka integration tests

### ISSUE THREAD

**Issue by mantzas** [beatlabs/patron#199]
## Is your feature request related to a problem? Please describe

In order to conduct integration tests with Kafka we should introduce Kafka and replace the MockBroker implementation.

## Describe the solution

Use dockertest to spin up kafka, run tests tear down.

**Comment by drakos74** [comment]
should we add some basic test scenarios we want to cover ?
It seems to me the scope can be potentially very big.
So it would seem reasonable to define it for the first iteration at least. 
WDYT ?

**Comment by mantzas** [comment]
I had in mind to actually remove the mock broker completely, add Kafka via dockertest, and change the existing tests to point to this Kafka instance making the test effectively a proper integration test.
