### ISSUE TITLE
Add route builder constructor functions with method

### ISSUE THREAD

**Issue by moukoublen** [beatlabs/patron#201]
## Is your feature request related to a problem? Please describe
Right now we have a builder pattern for route creation and HTTP method is being added with a  method. Having the method at the end of line could possible lead to not easy readable block of code.

## Describe the solution
Add more route constructor functions with the method name predefined e.g. `NewGetRouteBuilder`.

**Comment by bhiravabhatla** [comment]
Hi @moukoublen,

I am new to patron, trying to pick up any easy issues and learn in the process :). 

By route constructor functions, do you mean something like below for all Methods

```
// NewGetRouteBuilder constructor
func NewGetRouteBuilder(path string, processor ProcessorFunc) *RouteBuilder{
	
	return NewRouteBuilder(path, processor).MethodGet()
}
```
CC - @mantzas

**Comment by mantzas** [comment]
@bhiravabhatla Yes the idea is to make some constructors more specific without braking changes.

**Comment by bhiravabhatla** [comment]
Will make changes and raise a PR. Would need feedback on the same.
