### ISSUE TITLE
Allow multiple values in the HTTP headers

### ISSUE THREAD

**Issue by astrikos** [beatlabs/patron#215]
## Is your feature request related to a problem? Please describe
Some applications (kubernetes apiserver in my case) might send headers like application/json, */* which are legit according to RFC 26116 section 4.2 (https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2).

The current version doesn't take that into account and is returning an error in the determineEncoding function instead of the json which would be expected in the above example.

## Describe the solution
Split and read multiple accept/content headers and then compare them to the list of values we allow.

## Additional context
The is a proposed fix in https://github.com/beatlabs/patron/pull/207

**Comment by tpaschalis** [comment]
Closing this issue since it was addressed in #207. Thanks once again @astrikos!
