### ISSUE TITLE
Investigation for the feasability of having a pluggable HTTP router

### ISSUE THREAD

**Issue by mantzas** [beatlabs/patron#216]
## Is your feature request related to a problem? Please describe

We are using httprouter hardcoded in our codebase. But it has limitations and we could investigate to make the HTTP router part pluggable.
We can provide after this a way to let the end-user decide which one they want to support.

**Comment by fpapadopou** [comment]
Some more details about the current http [router](https://github.com/julienschmidt/httprouter)'s limitations:
The httprouter is very strict when interpreting route path segments. Consider the following
```go
    router.GET("/user/:id_user", nil)
    router.GET("/user/me/:profile", nil)
```
In the above case, the `me` static route segment conflicts with the `:id_user` wildcard, which will result in a a panic error.

The issue has been reported [here](https://github.com/julienschmidt/httprouter/issues/183) and will be addressed in version 2 of the `httprouter` library. Still, "lenient" interpretation of route segments will be an optional feature.

In the meantime, if you happen have the above issue, you can try sth like [this](https://github.com/julienschmidt/httprouter/issues/183#issuecomment-535245927).

**Comment by mantzas** [comment]
HTTP v2 support this OOTB.
