### ISSUE TITLE
Introduce Media Type API Versioning

### ISSUE THREAD

**Issue by fpapadopou** [beatlabs/patron#220]
## Is your feature request related to a problem? Please describe
Media type versioning can be achieved by manually processing headers in your app, but is not provided out of the box by the framework.

It doesn't have to be the only versioning type supported by the framework, but we could at least investigate whether it's worth implementing.

## Describe the solution

Media type versioning could look sth like this:
`Accept: application/x.my.org+json;version=2`
or this
`Content-Type: application/x.my.org+json;version=2`

Here is [an example](https://opensource.zalando.com/restful-api-guidelines/#114) from Zalando's API guidelines.

## Additional context

The implementation **must** be compatible with the [RFC](https://tools.ietf.org/html/rfc2616#section-3.7).

**Comment by fpapadopou** [comment]
@mantzas can you please review this issue?
Thanks!

**Comment by mantzas** [comment]
Versioning can be achieved with multiple strategies. Patron, especially the v2 HTTP component, gives full freedom to follow whatever convention makes sense. Goal is not to be too opinionated when it does not need to be. Thanks for the idea though.
