### ISSUE TITLE
Add optional gzip compression for HTTP responses

### ISSUE THREAD

**Issue by superstas** [beatlabs/patron#223]
## Is your feature request related to a problem? Please describe

We have a service that uses Patron with big JSON responses ( tens and hundreds of kilobytes ).
It would be useful to have the gzip compression out-of-box if a caller sends "Accept-Encoding: gzip" header.

WDYT?

**Comment by mantzas** [comment]
Sounds like a nice idea for a middleware maybe?

**Comment by superstas** [comment]
@mantzas, yes - I think middleware is a perfect fit here.
Should we label this issue as `enhancement`?

**Comment by KenanBek** [comment]
I will take this over if no objections. As I mentioned before, we already added GZIP middleware in our mServices. So, if it sounds good, I can move it to Patron.

But I expect it **not** to be included by default.

**Comment by drakos74** [comment]
> I will take this over, if no objections. As I mentioned before, we already added GZIP middleware in our mServices. So, if it sounds good I can move it to Patron.
> 
> But I expect it to **not** be included by default.

Exactly! You can create the middleware, an d users can add it when they are building the route

**Comment by azarakovskiy** [comment]
@KenanBek @superstas hey guys, any movement here?
I was about to add this to patron but then found this issue.

**Comment by superstas** [comment]
@KenanBek was going to implement it. Let's wait for his answer.

**Comment by KenanBek** [comment]
@azarakovskiy we stopped this because of some internal changes. But, since most of the code-base already in place, I will send this PR today for the review.
