### ISSUE TITLE
Proposal: Add "path" tag for decoding URN parameters into struct fields.

### ISSUE THREAD

**Issue by superstas** [beatlabs/patron#235]
Hi there,

## Is your feature request related to a problem? Please describe

Let’s assume we have an endpoint: `UPDATE /v1/user/:id` with body `{"name": string, "age": int}`

Usually there is a struct that represents this request that looks like
```go
type UpdateUserRequest struct {
	ID   int
	Name string `json:"name"`
	Age  int    `json:"age"`
}
```

Handlers usually do this:
```go
func (r *Router) updateUser(ctx context.Context, req *http.Request) (*http.Response, error) {
        var r UpdateUserRequest
        if err := req.Decode(&r); err != nil {
            return nil, errors.New("failed to decode request")
        }

        // check if the param is there 
        s, ok := req.Fields["id"]
		if !ok {
			return nil, errors.New("id is not found")
		}
		id, err := strconv.Atoi(s)
		if err != nil {
			return nil, errors.New("id is not an integer")
		}

        // assigning ID to the struct
        r.ID = id

        // validating
        if err := r.Validate(); err != nil {
           return nil, err
        }

        // finally at this point it's possible to use the structure
}
```

In case of a request without the body ( e.g.,`GET /v1/user/:id`  ) using req.Fields["id"] is more or less bearable. 

But in the case when a request has the body in JSON like in the example - it’s getting inconvenient ( another case when endpoint looks like `POST /v1/user/:group_id/:id` ).

The actual implementation depends from case to case but what’s in common is a pretty boilerplate part of converting string representation into integers + merging with “request” struct

## Describe the solution

I’d like to propose is using tags. Imagine that we have this struct

```go
type UpdateUserRequest struct {
	ID   int    `path:"id"` <<<<-- here's a hint for Patron to map `:id` from URN onto this field
	Name string `json:"name"`
	Age  int    `json:"age"`
}
```

In this case a handler could look like
```go
func (r *Router) updateUser(ctx context.Context, req *http.Request) (*http.Response, error) {
        var r UpdateUserRequest
        if err := req.Decode(&r); err != nil {
            return nil, errors.New("failed to decode request")
        }

        // validating
        if err := r.Validate(); err != nil {
           return nil, err
        }

        // finally at this point it's possible to use structure
}
```

What do you think about this proposal?

Thank you.

**Comment by mantzas** [comment]
The above proposal will handle only JSON. Another encoding is not supported.

**Comment by superstas** [comment]
Hey @mantzas,

We've discussed that adding a feature like that would require reflection so we need to be careful given that decoding part is the most performant part.

I've sketched the initial decoding implementation and compared it with other in benchmarks to have some numbers.

```go
func DecodePath(fields map[string]string, v interface{}) error {
	structType := reflect.TypeOf(v).Elem()
	for i := 0; i < structType.NumField(); i++ {
		f := structType.Field(i)
		tagName, ok := f.Tag.Lookup("path")
		if !ok {
			continue
		}

		value, ok := fields[tagName]
		if !ok {
			continue
		}

		field := reflect.ValueOf(v).Elem().FieldByName(f.Name)
		if !field.CanSet() {
			continue
		}

		switch field.Kind() {
		case reflect.Int:

			i, err := strconv.Atoi(value)
			if err != nil {
				return err
			}

			if !field.OverflowInt(int64(i)) {
				field.SetInt(int64(i))
			}
		}
	}

	return nil
}
```

https://play.golang.org/p/BLSi8hunn7b

I've checked this implementation with these tests

```go
func BenchmarkDecodePath(b *testing.B) {
        type user struct {
                ID  int `path:"id"`
                Age int `json:"age"`
        }

        fields := map[string]string{"id": "123"}

        var u user
        for i := 0; i < b.N; i++ {
                DecodePath(fields, &u)
        }
}

func BenchmarkDecodePathWithTwoParams(b *testing.B) {
        type user struct {
                ID  int `path:"id"`
                Age int `path:"age"`
        }

        fields := map[string]string{"id": "123", "age": "123"}

        var u user
        for i := 0; i < b.N; i++ {
                DecodePath(fields, &u)
        }
}
```

The numbers:
```
BenchmarkDecodePath-16                   6024147               200 ns/op              24 B/op          3 allocs/op
BenchmarkDecodePath-16                   5868000               203 ns/op              24 B/op          3 allocs/op
BenchmarkDecodePath-16                   6106642               196 ns/op              24 B/op          3 allocs/op
BenchmarkDecodePathWithTwoParams-16      4081267               295 ns/op              32 B/op          4 allocs/op
BenchmarkDecodePathWithTwoParams-16      3926041               297 ns/op              32 B/op          4 allocs/op
BenchmarkDecodePathWithTwoParams-16      3987373               296 ns/op              32 B/op          4 allocs/op
```

I've also checked `json.Decode` and `json.DecodeRaw` functions for comparing the numbers

Tests:
```go
func BenchmarkDecode(b *testing.B) {
        type user struct {
                ID  int `json:"id"`
                Age int `json:"age"`
        }

        body := `{"id": 1, "age": 50}`

        r := bytes.NewBuffer(make([]byte, 1024))
        for i := 0; i < b.N; i++ {
                Decode(r, body)
        }
}

func BenchmarkDecodeRaw(b *testing.B) {
        type user struct {
                ID  int `json:"id"`
                Age int `json:"age"`
        }

        body := `{"id": 1, "age": 50}`

        var u user
        for i := 0; i < b.N; i++ {
                DecodeRaw([]byte(body), &u)
        }
}
```

The numbers:
```
BenchmarkDecode-16                       5862260               207 ns/op             880 B/op          3 allocs/op
BenchmarkDecode-16                       5870074               212 ns/op             880 B/op          3 allocs/op
BenchmarkDecode-16                       5804023               206 ns/op             880 B/op          3 allocs/op
BenchmarkDecodeRaw-16                    1872483               692 ns/op             240 B/op          5 allocs/op
BenchmarkDecodeRaw-16                    1761625               678 ns/op             240 B/op          5 allocs/op
BenchmarkDecodeRaw-16                    1796917               670 ns/op             240 B/op          5 allocs/op
```


So based on the numbers the reflection option doesn't seem drastically slower. I think we can go with reflection implementation.

Before we discuss the implementation details, what do you think about the numbers? Does it make sense?

Thank you.

**Comment by drakos74** [comment]
would it be possible to highlight the structs somehow ? So that in the case where we have no path properties, we can use the previous approach ?

**Comment by superstas** [comment]
Hey @drakos74 , thanks for the reply.

By `highlight the structs` do you mean some clarity on API perspective?

**Comment by mantzas** [comment]
@superstas Keep in mind that the fields map contains also query parameters and not only route variables. Would that pose a problem?

**Comment by superstas** [comment]
@mantzas that's a very good point! I've missed this detail.

I've taken a look at the current logic in [handler.go#27](https://github.com/beatlabs/patron/blob/master/component/http/handler.go#L27)

What we do is:
1) Parse the query params
2) Parse the route params

Both steps share the same map, so the overlapping with keys is possible.

Let's say we have a query`?id=1&name=test` with a route `GET /v1/api/user/:id` and the whole URN looks like `GET /v1/api/user/123?id=1&name=test`

- After the 1st  step, the map would have 
`{"id": "1", "name": "test"}`

- After the 2nd step, the map would be 
`{"id": "123", "name":"test"}`

We have the overlapping with `id`. It's an edge case.

So, I wouldn't say it's a problem. 
Probably it's even better: "extra" advantage - mapping query params onto struct fields as well.

What do you think about it? Do you think it's an issue?

**Comment by mantzas** [comment]
So we will support route and query params in one swoop.
Also, this is will be a helper method and you can use it only if somebody wants it.
Maybe also do a helper method that takes the struct to be filled and the http.request and just does everything e.g. route and query param mapping and decoding of the body in one swoop.
Would that make sense?

**Comment by superstas** [comment]
@mantzas , it makes sense.

What do you think about adding this helper as a method to `http.Request` type ( https://github.com/beatlabs/patron/blob/master/component/http/http.go#L12 ) that could look like

```go
func (r *Request) DecodeWithPath(v interface{}) error {
        if err := r.decodePath(r.Fields, v) ; err !=nil {
            return err
        }
	return r.decode(r.Raw, v)
}
```
And an endpoint could look like
```go
func (r *Router) updateUser(ctx context.Context, req *http.Request) (*http.Response, error) {
        var r UpdateUserRequest
        if err := req.DecodeWithPath(&r); err != nil { // instead of req.Decode(&r)
            return nil, errors.New("failed to decode request")
        }
        ...
}
```

I've have got two questions:
1) Would this place fit? Is there a better place for this helper?
2) In case when `r.decode` is protobuf implementation it no makes sense to run  `r.decodePath`, but in `Request` there is no way to distinguish the particular implementation of `decode` ( since it has the same func type `encoding.DecodeFunc` ). So does it make sense to care about it or we leave it on end developer common sense?

**Comment by mantzas** [comment]
Since we do not support anything other than JSON we cannot make it generic on the request.
The whole code has to live inside the `http` package probably inside a `json` sub-package...
If we had a solution that would cover all our supported need we could add it there.
And since we support also custom encoding to be supplied by the developer this would not make sense at all.
TBH the whole addition of this seems not to make any hug difference and it only applies partially to what we support now.
I am not very convinced, but let's see what the other guys say about this.... @drakos74 @tpaschalis ???

**Comment by drakos74** [comment]
> Hey @drakos74 , thanks for the reply.
> 
> By `highlight the structs` do you mean some clarity on API perspective?

@superstas i mean to be able to avoid the reflection if there is no need for it.

**Comment by drakos74** [comment]
@mantzas , @superstas , I personally don't see any major reason to add this as a default behaviour. (Except if i am missing something). I agree about reducing the boilerplate, just i would propose to make this optional (e.g. have the "helper" method for whoever would like to use it). Would it make sense to you @superstas , and would it also be possible to make this without changing the current API ?

**Comment by mantzas** [comment]
@superstas We had a chat with the other curators and we agree that this is a nice addition as a helper functionality since it is not generaic enough to apply to other types on encoding as well. It could live inside HTTP package as a subpackage and since it handles just JSON we shoudl also name it `json`. Are you ok with this?

**Comment by superstas** [comment]
Hey @mantzas @drakos74 

Thank you for your valuable comments and feedback.
I completely agree that this functionality should be optional.
Also to me, it sounds reasonable to put implementation to `http/json` subpackage.

So, sounds like we reach the consensus. I'll send PR with implementation if you don't mind.

Thank you.

**Comment by mantzas** [comment]
@superstas Hey, we have released HTTP v2 which is a thin layer over std HTTP and does not provide any other functionality. This feature is now not applicable anymore and I will close it. Please check out HTTP v2 which you have to opt in until we make it the default one.
Thanks for the participation.
