### ISSUE TITLE
Update README example section and point to examples folder

### ISSUE THREAD

**Issue by c0nstantx** [beatlabs/patron#25]
## Is your feature request related to a problem? Please describe

In `README` file, the provided [example](https://github.com/thebeatapp/patron#example) needs to be revised. 
Notions like `package aliasing`, `function type implementation`, `interface implementation` etc. are considered prerequisites. That makes it more difficult for developers with not enough experience in *Go* to start a new project and be familiarised with [Patron](https://github.com/thebeatapp/patron).

Also in `patron-cli` generated code, it could be useful to implement some demo routes that will be initially commented out. These routes would be fully functional if comments were removed.

These kind of practices with working examples makes newcomers productive in shorter time and framework understanding easier.

## Describe the solution

The solution would be to update current `README` example with functional code out of the box.
Also, a few working routes (initially commented out) could be integrated at `patron-cli` generation process.

**Comment by mantzas** [comment]
@c0nstantx could you pls provide the revised example to check out what you mean? 
A service might not have the need for routes at all so providing with boilerplate code might not be that great. Check out PR https://github.com/thebeatapp/patron/pull/15 which introduces some boilerplate code from patron-cli.

**Comment by c0nstantx** [comment]
@mantzas Regarding routes in boilerplate code I though it could be a "nice to have" since the majority of services built with patron are REST APIs.
Below is the example I had in mind:

```go
package main

import (
  "fmt"
  "os"

  "github.com/thebeatapp/patron"
  "github.com/thebeatapp/patron/log"
  sync_http "github.com/thebeatapp/patron/sync/http"
)

var (
  version = "dev"
)

func main() {
  name := "test"

  err := patron.Setup(name, version)
  if err != nil {
    fmt.Printf("failed to set up logging: %v", err)
    os.Exit(1)
  }

  // Set up HTTP routes
  routes := make([]sync_http.Route, 0)
  // Append a GET route
  routes = append(routes, sync_http.NewRoute("/get", http.MethodGet, func(ctx context.Context, req *sync.Request) (*sync.Response, error) {
    return sync.NewResponse("Get data"), nil
  }, true, nil))
  srv, err := patron.New(name, version, patron.Routes(routes))
  if err != nil {
    log.Fatalf("failed to create service %v", err)
  }

  err = srv.Run()
  if err != nil {
    log.Fatalf("failed to run service %v", err)
  }
}
```

**Comment by c0nstantx** [comment]
@mantzas This is what I was thinking for generated code from `patron-cli`:

```go
package main

import (
	"fmt"
	"os"

	"github.com/thebeatapp/patron"
	"github.com/thebeatapp/patron/log"
)

var (
	version = "dev"
)

func main() {
	name := "{{name}}"

	err := patron.Setup(name, version)
	if err != nil {
		fmt.Printf("failed to set up logging: %v", err)
		os.Exit(1)
	}

	routes := make([]sync_http.Route, 0)

	// Example routes. Uncomment to use

	// Get route with tracing and no authentication
	// routes = append(routes, sync_http.NewRoute("/get", http.MethodGet, func(ctx context.Context, req *sync.Request) (*sync.Response, error) {
	// 	return sync.NewResponse("Get data"), nil
	// }, true, nil))

	// Post route with tracing and failed authentication
	// routes = append(routes, sync_http.NewRoute("/post", http.MethodPost, func(ctx context.Context, req *sync.Request) (*sync.Response, error) {
	// 	return sync.NewResponse("Success"), nil
	// }, true, demoAuthenticator{Authenticated: false}))

	// Put route without tracing and failed authentication
	// routes = append(routes, sync_http.NewRoute("/put_unauthenticated", http.MethodPut, func(ctx context.Context, req *sync.Request) (*sync.Response, error) {
	// 	return sync.NewResponse("Success"), nil
	// }, false, demoAuthenticator{Authenticated: false}))

	// Put route without tracing and successfull authentication using helper method NewAuthPutRoute
	// routes = append(routes, sync_http.NewAuthPutRoute("/put_authenticated", func(ctx context.Context, req *sync.Request) (*sync.Response, error) {
	// 	return sync.NewResponse("Success"), nil
	// }, false, demoAuthenticator{Authenticated: true}))

	srv, err := patron.New(name, version, patron.Routes(routes))
	if err != nil {
		log.Fatalf("failed to create service %v", err)
	}

	err = srv.Run()
	if err != nil {
		log.Fatalf("failed to run service %v", err)
	}
}

// Uncomment for use on route examples with authenticator
// type demoAuthenticator struct {
// 	Authenticated bool
// }

// func (a demoAuthenticator) Authenticate(req *http.Request) (bool, error) {
// 	return a.Authenticated, nil
// }
```

We could create an example for more advanced route usage and don't add it to boilerplate.

**Comment by mantzas** [comment]
@c0nstantx i see. I propose to extend the  PR https://github.com/thebeatapp/patron/pull/15 and support HTTP also, which would create the above code as actual code.
this would mean that is the user request to ass HTTP as a component the above code will be included and will not be documented at all.
Kafka and AMQP options already generated boilerplate code. Would you like to add the code to the mentioned PR?

**Comment by c0nstantx** [comment]
@mantzas Extending PR #15 would do just fine for HTTP boilerplate and I 'd be happy to add the code needed.
But I still would like to update the documentation and create a more intuitive set of examples. A separate section of example(s) for each package would be even better if you agree.

**Comment by mantzas** [comment]
@c0nstantx i have updated the issue https://github.com/thebeatapp/patron/issues/6. 
Keep in mind that a examples folder exists with all supported components, with a ready for use docker-compose file in order to see the framework in action. 
Future components should be included in the examples folder in order to show off all the capabilities of the framework and in order to be used as a guideline for implementation.
Since we have all examples already and maintaining documentation is a big burden i propose to:
- Clean up the example code snippet, based on your proposal
- Add a link to the examples folder and point the reader to it.
Documentation has a high maintenance cost and i am pretty sure that the current one already is a little bit out of sync. :(

**Comment by c0nstantx** [comment]
@mantzas It sounds great. I will change the title of the issue to match your proposal.
