### ISSUE TITLE
Kafka Batch Consumer

### ISSUE THREAD

**Issue by tpaschalis** [beatlabs/patron#260]
## Is your feature request related to a problem? Please describe

Patron's current implementation of Kafka consumers does not support message batching. Adding such functionality would enable certain workloads to become more efficient. 

Since transactional guarantees are not something that is supported by Sarama, any clients using this functionality should be able to work with  *at least once* deliveries.

## Is this a bug? Please provide steps to reproduce, a failing test etc.
No. 

## Describe the solution

We've had a few discussions about the best way to move forward with the task; the key outcomes were

- Kafka's streaming logic is different than the message broker logic of AMQP and SNS/SQS. Trying to contain both under a single abstraction is not ideal.
- Instead of maintaining the current abstraction, we've decided to introduce a new Kafka package for simple, group and batch consumers.
- This new package will be more transparent in regards to Sarama; exposing more its internals, plus with QoL helpers for the end-users.
- The 'old' Kafka package will be left up until end-users migrate to the new one, but will be deprecated after proper communication.
- We'll also have to write some guidelines for people wanting to upgrade Patron and use the new consumer, if there are breaking changes

## Additional context

Sarama has introduced support for manual committing, which could be promising.

**Comment by oss92** [comment]
I will pick up this issue.
