### ISSUE TITLE
Proposal: Introduce rate-limiting middleware

### ISSUE THREAD

**Issue by tpaschalis** [beatlabs/patron#263]
## Is your feature request related to a problem? Please describe
When a Patron-powered microservice is exposed to the internet, some kind of rate-limiting mechanism can be useful.

In practice, rate-limiting can be handled by many means : a proxy like NGINX/Apache/HAProxy, a Kubernetes Ingress, or even some SaaS solutions like Cloudflare or AWS WAF. 

However, we might want to support rate-limiting at an application level as well.

## Is this a bug? Please provide steps to reproduce, a failing test etc.
Nope.

## Describe the solution
The simplest solution is a middleware implementing a token bucket algorithm that slows down or returns 429 status codes when the limit is reached. It could be useful for someone who wants to dive into how Patron middlewares work, and should be straightforward to test as well.

## Additional context
The idea is to create two types of rate-limiting middlewares; one for single-machine contexts (eg. a single Patron deployment), and one for distributed-context uses (eg. when having multiple Patron deployments with a load balancer, or a Patron application deployed in kubernetes pods). The first one would use an atomic counter as a variable, while the second would use something like Redis' [INCR](https://redis.io/commands/incr)

Here's how I start implementing a *local* version of the rate-limiting functionality
- Step 0 : Read the existing Patron middleware implementations to see how they're built.
- Step 1 : Build a passthrough middleware that does nothing; just prints out the content of received requests
- Step 2 : Introduce an atomic counter that is increased whenever the middleware is called
- Step 3 : Return [429 - Too many requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429) when that counter gets to 10. Maybe introduce a temporary way to reset the counter to zero for manual testing.
- Step 4 : Set up a simple [Token Bucket](https://en.wikipedia.org/wiki/Token_bucket) algorithm which will return 429 whenever the bucket is full
- Step 5 (Optional) : Set up an interface so that people can implement their own rate-limiting algorithms.

**Comment by bhiravabhatla** [comment]
@tpaschalis  - I would like to work on this. I am new to golang development, so might take sometime and feedback to complete this :)

**Comment by tpaschalis** [comment]
@bhiravabhatla thanks for the initiative! You can take a stab; I'll try to provide some help so we can incrementally build something.

Don't worry if you get stuck, we can reuse your work in the future and/or improve other parts of the projects as well!

I've updated the *Additional Context* section of the description with how I'd start building something like this off the top of my head. Let me know how this sound, if you have any other questions, or if I can do something else to help you get started!

**Comment by bhiravabhatla** [comment]
@tpaschalis  - Sorry for the delay on this. Have been stuck with some work, could not spend time on this. I spent sometime today, will try to raise a WIP PR for some feedback soon. Apologies for delay!

**Comment by bhiravabhatla** [comment]
@tpaschalis  Implemented a simple rate limiter in the PR. Kindly share your feedback.

**Comment by bhiravabhatla** [comment]
@tpaschalis  - Any feedback would be helpful, have weekend coming - can spend sometime :)

**Comment by tpaschalis** [comment]
Hey Santosh! Sorry for not being able to provide feedback until now, I didn't find the time to checkout and play with the new middleware. I'll make sure to have a review ready by the end of the week.

**Comment by bhiravabhatla** [comment]
No issues, no hurry :)
