### ISSUE TITLE
Cannot start 'seventh' and 'sixth' example together

### ISSUE THREAD

**Issue by tpaschalis** [beatlabs/patron#277]
## Is your feature request related to a problem? Please describe
The sixth and seventh example are both using port 50006 for a GRPC and an HTTP endpoint respectively. That means that they cannot be launched together.

## Is this a bug? Please provide steps to reproduce, a failing test etc.

Change into the patron/examples directory and try to run 
```go
$ go run sixth/main.go
$ go run seventh/main.go 
{"lvl":"debug","host":"Paschalis-Tsilias.local","srv":"seventh","ver":"1.0.0","time":"2020-10-21T17:00:00.381556+03:00","src":"patron/service.go:121","msg":"closing tracer"}
2020/10/21 17:00:00 failed to create and run service listen tcp :50006: bind: address already in use

$ go run seventh/main.go 
$ go run sixth/main.go
{"lvl":"fatal","host":"Paschalis-Tsilias.local","srv":"sixth","ver":"1.0.0","time":"2020-10-21T17:00:09.284834+03:00","src":"runtime/proc.go:204","msg":"failed to create and run service: failed to listen: listen tcp :50006: bind: address already in use\n"}
```

## Describe the solution

Use a different port for the 'seventh' example which showcases the server-side caching. This change should be reflected to the 'first' example and the `DoTimingRequest` function.

## Additional context
None, for now.

**Comment by drakos74** [comment]
seems there was a race condition for the port iterator 😂

**Comment by bhiravabhatla** [comment]
Attempted fixing this issue. Kindly provide feedback.
