### ISSUE TITLE
Live and Ready endpoint support

### ISSUE THREAD

**Issue by mantzas** [beatlabs/patron#28]
## Is your feature request related to a problem? Please describe

We have to introduce readiness and liveness endpoint to support checks from kubernetes and other systems.

The liveness indicates that the service is running correctly. Any code greater than or equal to 200 and less than 400 indicates success. Any other code indicates failure.
The endpoint will, by default return 200 and will let the developer change this to 500 on demand.
The actual endpoint will be **/alive**.

The readiness indicates that the service can accept incoming traffic. The endpoint will, by default return 200 and will let the developer change in order to transition from 500 to 200.
The endpoint for readiness will be **/ready**.

The existing /health endpoint will be removed.

## Additional context

There is already a issue https://github.com/thebeatapp/patron/issues/24 which tries to introduce the healthiness concept in components. If the above works as design we should not implement the change in the component since it will introduce a lot of unneeded complexity.

**Comment by apanagiotou** [comment]
Sounds good. I also propose:

1. Do not implement any logic on **live** endpoint. It should return status 200 if the process is running and 5xx if is not.
2. Implement logic in **ready** endpoint. Check the availability of backend dependencies, or make a "full path" check.

**Comment by mantzas** [comment]
@apanagiotou after a quick talk with your guys we should avoid any dependency check in any endpoint since they might introduce latency. The proposed implementation will not do anything except allow the developer to set the desired responses of the endpoints. By default both will return 200 OK.

**Comment by cpapidas** [comment]
Sound good to me, I totally agree to replace the /health endpoint with /alive and /ready. 
Maybe we will have breaking changes.

**Comment by mantzas** [comment]
@asenlog  Done, enjoy! If you need any help to understand let me know.
