### ISSUE TITLE
Examples 4 and 5 are failing due to breaking changes in localstack

### ISSUE THREAD

**Issue by bhiravabhatla** [beatlabs/patron#282]
## Is your feature request related to a problem? Please describe

This is a bug

## Is this a bug? Please provide steps to reproduce, a failing test etc.

Example 4 and 5  interact with SQS and SNS exposed using localstack. Currently we use -> awsSQSEndpoint = "http://localhost:4576" and awsSNSEndpoint = "http://localhost:4575".

There is a breaking change in localstack - All the aws mock services are exposed at single port (4566) now (https://github.com/localstack/localstack#announcements). Example 4 and 5 are failing due to this.

## Describe the solution

As all the services are exposed using single port in localstack now - we can change the docker-compose service config for it bind only 4566

```
networks:
      examplenw:
        aliases:
          - localstack
    ports:
      - "4566:4566"

```
Also, change all localstack endpoints to use 4566 port. 

## Additional context

To avoid such unforeseen issues in future, we could look at locking down image tags for all our services in docker-compose. Need feedback on this.

**Comment by tpaschalis** [comment]
> To avoid such unforeseen issues in future, we could look at locking down image tags for all our services in docker-compose.

I understand that view on locking image tags. 

But on the other hand, I'd expect users (especially newcomers) to use the latest versions of any dependencies, so this is a good opportunity for us to spot breaking changes like this one.

**Comment by mantzas** [comment]
@tpaschalis i actually agree on the locking our dependencies because it is the only way to guarantee repeatability..
