### ISSUE TITLE
Flaky test in Test_SNS_Publish_Message

### ISSUE THREAD

**Issue by tpaschalis** [beatlabs/patron#284]
## Is your feature request related to a problem? Please describe

No.

## Is this a bug? Please provide steps to reproduce, a failing test etc.

Probably. A recent CI run reported a data race on `Test_SNS_Publish_Message`.
I triggered a re-run and it passed. It's quite curious, as it's the first time that I've seen a *flaky race detector triggering*. Do we have any other explanation, am I missing something obvious here?

https://github.com/beatlabs/patron/pull/280/checks?check_run_id=1300120643

## Describe the solution

Needs Investigation

## Additional context

None, for now.

**Comment by mantzas** [comment]
@tpaschalis Hey, it seem that the last months the builds are working fine. Is this still valid?
