### ISSUE TITLE
Panic when starting service with no logger

### ISSUE THREAD

**Issue by tpaschalis** [beatlabs/patron#285]
## Is your feature request related to a problem? Please describe

No.

## Is this a bug? Please provide steps to reproduce, a failing test etc.

With the introduction of a new logger functionality in #259 I noticed some of the examples panicking. 

In the release notes we say that
> Keep in mind that if no logger is provided it will use the default structured logger

But it seems that services that are set up without a logger instead panic.

Right now, examples `second`, `fourth` and `fifth` panic for this exact cause.

Here's what happens for me locally in the examples, or if I run `service, err := patron.New(name, version)`

```
$ go run fourth/main.go
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x164234b]

goroutine 1 [running]:
github.com/rs/zerolog.(*Logger).should(0x0, 0x16da301, 0xc)
	/Users/paschalistsilias/go/pkg/mod/github.com/rs/zerolog@v1.5.0/log.go:358 +0x2b
github.com/rs/zerolog.(*Logger).newEvent(0x0, 0x1010101, 0x0, 0x16da380)
	/Users/paschalistsilias/go/pkg/mod/github.com/rs/zerolog@v1.5.0/log.go:337 +0x3e
github.com/rs/zerolog.(*Logger).Info(...)
	/Users/paschalistsilias/go/pkg/mod/github.com/rs/zerolog@v1.5.0/log.go:241
github.com/beatlabs/patron/log/zerolog.(*Logger).Infof(0xc00000eda0, 0x17f09aa, 0x2f, 0xc00007e3f0, 0x3, 0x3)
	/Users/paschalistsilias/Beat-repos/patron/log/zerolog/logger.go:108 +0x3d
github.com/beatlabs/patron/log.Infof(...)
	/Users/paschalistsilias/Beat-repos/patron/log/log.go:150
github.com/beatlabs/patron.setupTracing(0x17d01eb, 0x6, 0x17cebfb, 0x5, 0x0, 0xc00007e390)
	/Users/paschalistsilias/Beat-repos/patron/service.go:305 +0x2fa
github.com/beatlabs/patron.setupObservability(0x17d01eb, 0x6, 0x17cebfb, 0x5, 0xc00007e390, 0x18d4e20, 0xc00000ed60, 0xc00002a0b0, 0xc00010fe68)
	/Users/paschalistsilias/Beat-repos/patron/service.go:271 +0x97
github.com/beatlabs/patron.New(0x17d01eb, 0x6, 0x17cebfb, 0x5, 0x0, 0x0, 0x0, 0x1cb2cf0, 0x1801cc0, 0xc00010feb8)
	/Users/paschalistsilias/Beat-repos/patron/service.go:228 +0x1e8
main.main()
	/Users/paschalistsilias/Beat-repos/patron/examples/fourth/main.go:71 +0x71
exit status 2
```

The panic starts on [this](https://github.com/beatlabs/patron/blob/3ba61f44574263cf2094a6e98b3232324cf3eb3b/service.go#L305) line, where we log something on a nil logger.

## Describe the solution

As we've discussed, we can keep the original idea of falling back to the default structured logger if no other option is provided.

Another idea would be to have a dummy no-op logger, but I'm not a big fan to be honest.

## Additional context

None, for now

**Comment by mantzas** [comment]
@tpaschalis good catch and i find the culprit. The sub logger creation for zerolog was false. Fixing it and writing some test and we do an urgent release to fix this.
