### ISSUE TITLE
It's not possible to change deflate compression level

### ISSUE THREAD

**Issue by azarakovskiy** [beatlabs/patron#302]
## Is your feature request related to a problem? Please describe

I want to have the possibility to override a default deflate level. It's hardcoded to `8` (`	deflateLevel        = 8`) in HTTP component builder. I want to be able to choose this value as it impacts the performance of my service and the size of a payload.

## Is this a bug? Please provide steps to reproduce, a failing test etc.

It's not a bug

## Describe the solution

I want to expose it using the env var in `service.go::createHTTPComponent()`, the same way as port and timeouts are exposed.
The builder method is already there. `b.WithDeflateLevel()`

## Additional context

I believe that it's just a good practice for a framework to have as little opinionated hardcoded values as possible. Everything or almost everything should be configurable in a good framework if we want other people to use it.

**Comment by drakos74** [comment]
Hi @azarakovskiy , thank you for your suggestion. I am wondering what is preferable ... expose many env properties or give the users the option to build their abstractions on top ? I would personally be inclined to follow the second ... facilitate users by simplifying configuration , but giving the option to extend and adjust. Personally i have no objection adding this in patron, if the others agree as well. I am just missing the added value here.

**Comment by azarakovskiy** [comment]
@drakos74 the added value is the ability to have fine-grained control over compression. Depending on a payload size it's sometimes better to compress less (save on computation time) and transfer a bigger payload to achieve better overall performance. This is a very service-specific thing and having an opinionated hardcoded value in patron makes it difficult to adjust the service to your specific needs.

Regarding the implementation. At this moment, [I'd say a simple exposure of an env var will suffice](https://github.com/taxibeat/authentication-service/pull/74/commits/7fd4edd3910dc7fbb41cb512238324f80b7ca050), because if you want to allow building configuration, then you must invest some good time to design the API properly.

**Comment by drakos74** [comment]
Maybe i am missing something, but in my understanding you can set the compression level in your service using the builder. Or even implement this in a wrapper reading a system property. On the other hand not having a default value and failing fast is an approach that one can take. I am personally not really convinced though. But lets see what @mantzas and @tpaschalis think on this as well.

**Comment by azarakovskiy** [comment]
At this moment, you can't override a default value with the rest of the default settings.
The default value is not `8` which is a strange value tbh.

Eight is computationally expensive and doesn't give much gain in size. A default value in Golang is `6` but even six is not ideal. However, some might prefer a smaller payload.

See here that 4 or 5 actually are better. https://blog.klauspost.com/rebalancing-deflate-compression-levels/ 
All such things are very specific to your needs and must not be hardcoded in a framework.

**Comment by drakos74** [comment]
i think you can always use `WithDeflateLevel(x)` when you build your route, based on your microservice requirement. But please correct me if i am wrong or i am missing something.

**Comment by azarakovskiy** [comment]
@drakos74 nope. 
![image](https://user-images.githubusercontent.com/4928787/100848385-51a31580-3481-11eb-828a-951640709684.png)

**Comment by drakos74** [comment]
there is an example in the tests. https://github.com/beatlabs/patron/blob/master/component/http/component_test.go#L166
Would this be helpful ?
```
gotHTTPComponent, err := NewBuilder().WithAliveCheckFunc(tc.acf).WithReadyCheckFunc(tc.rcf).
				WithPort(tc.p).WithReadTimeout(tc.rt).WithWriteTimeout(tc.wt).
				WithDeflateLevel(tc.dl).
				WithRoutesBuilder(tc.rb).
				WithMiddlewares(tc.mm...).WithSSL(tc.c, tc.k).WithShutdownGracePeriod(tc.gp).Create()
```

**Comment by azarakovskiy** [comment]
Yes, it's technically possible, but it looks like an overhead if I want the rest of things to be set to the default value.

**Comment by mantzas** [comment]
@drakos74 We need to build the method at the service level since patron starts an internal HTTP server on the service builder actually...

**Comment by azarakovskiy** [comment]
@mantzas maybe start with the low-hanging fruit that's already ready? https://github.com/taxibeat/authentication-service/pull/74/commits/7fd4edd3910dc7fbb41cb512238324f80b7ca050 ;)

**Comment by mantzas** [comment]
We should probably use one of the options and we use the service builder just to be consistent. The change is fairly trivial, just one hour of work...

**Comment by azarakovskiy** [comment]
I mean, the env var exposure can also be considered as a consistent approach since there are already a couple of properties exposed this way. And to be honest, this is more convenient as it allows an easy redeploy with a new setting without building the env var management in your service's code.

**Comment by azarakovskiy** [comment]
Shall I make a PR then?

**Comment by mantzas** [comment]
let's wait for @drakos74 and @tpaschalis...
