### ISSUE TITLE
Allow for a way to overwrite the default histogram buckets for http metrics

### ISSUE THREAD

**Issue by peterklijn** [beatlabs/patron#338]
## Is your feature request related to a problem? Please describe

Patron uses the jaeger client for tracing, which also does metrics. The default metrics that it exposes use the following histogram buckets for response times:

```
0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1, 2.5, 5, 10, +Inf
```

These probably make sense for fast services, but in the case where the requests are slow (for example when you're depending on other service calls that are slow), the metrics are not accurate enough with these values, even misleading:

If a request is 251ms, it goes in the 500ms bucket
If a request is 501ms, it goes in the 1s bucket.

So, it doesn’t give an accurate representation of the data, especially if you then visualise this tools like in Grafana.

For services like this, it would be nice if we can overwrite the default buckets to fit the specific service needs better.

## Describe the solution

Allow a way to set different buckets as defaults, if specified these will be set within Patron, otherwise it will use the defaults.

Either via a builder style, or environment variables.

**Comment by tpaschalis** [comment]
Indeed, these are the [default buckets](https://github.com/prometheus/client_golang/blob/d89cf5af8849fcb6d69f2c16bdf3b910e03d341e/prometheus/histogram.go#L63) defined in Prometheus.

The metrics factory in jaeger-lib supports a [WithBuckets](https://github.com/jaegertracing/jaeger-lib/blob/78a0e7f3cd0c2ab3f747af150d98f534879f09f3/metrics/prometheus/factory.go#L67) option; we should find a nice way to use this option when initializing metrics in our tracing component, [here](https://github.com/beatlabs/patron/blob/932280919ab49017635d8be5572447950537db18/trace/trace.go#L52).

> the metrics are not accurate enough with these values, even misleading
> If a request is 251ms, it goes in the 500ms bucket
> If a request is 501ms, it goes in the 1s bucket.

In any case, these number represent the upper-limit of each bucket, but the intervals could be customized to fit our needs.

**Comment by moraitisk** [comment]
I'd like to work on this

**Comment by mantzas** [comment]
@moraitisk pls do!
