### ISSUE TITLE
Kafka sync producer with trace support

### ISSUE THREAD

**Issue by mantzas** [beatlabs/patron#36]
## Is your feature request related to a problem? Please describe

A synchronous producer is needed in order to simplify sending messages to Kafka without having to monitor for errors in a channel.
The producer should propagate distributed traces.

**Comment by gm42** [comment]
I would like to submit a PR for this.

**Comment by mantzas** [comment]
@gm42 there is already a PR running for months. Please get in contact with @avalsamis about this because this is stalled months now.
Maybe he is ok with deleting the PR and you can start again because it has merge conflicts.

**Comment by gm42** [comment]
@mantzas ah! good to know, I will, thanks. Ideally I would like to not throw away the work already done, perhaps I can still pick it up and solve the conflicts/problems.
