### ISSUE TITLE
Incompatible Go version

### ISSUE THREAD

**Issue by tsauvajon** [beatlabs/patron#366]
## Problem

This project says it's running on Go 1.13: https://github.com/beatlabs/patron/blob/master/go.mod#L32, but when running `go vet` on Go 1.13 I get the following:
```sh
# github.com/beatlabs/patron/log/std
vet: log/std/logger.go:82:99: Lmsgprefix not declared by package log
```

`log.Lmsgprefix` was introduced in 1.14. Updating to Go version 1.14+ (I tried with `1.16.3`) fixes the problem.

You can reproduce with:
```sh
docker run -v $(PWD):/src --workdir="/src" golang:1.13.8 go vet ./...
```

## Solution

Update `go.mod` to at least go `1.14`

**Comment by gmaz42** [comment]
Would it be an idea to make sure that the GitHub action uses the version specified in `go.mod` to build?

**Comment by mantzas** [comment]
Github actions is already on 1.14.

**Comment by mantzas** [comment]
We are already on 1.16. closing this.
