### ISSUE TITLE
Metrics/Traces provider agnostic design

### ISSUE THREAD

**Issue by drakos74** [beatlabs/patron#368]
## Is your feature request related to a problem? Please describe

Evaluate and make use of a provider agnostic approach to metrics and traces

## Describe the solution

Check opentelemetry (https://opentelemetry.io/) or opencensus (https://opencensus.io/) frameworks for logging and tracing. 
## Additional context

Patron could still use a prometheus and jaeger exporter for each as default. but would open and allow more transparent switching between metric providers.

**Comment by mantzas** [comment]
@drakos74 I am also for changing to an agnostic solution and opentelemetry is the way to go because it is actually replacing opentracing and oepncensus. Unfotunately it is still in BETA IIRC so we have to wait for some time.

**Comment by mantzas** [comment]
OpenTelemetry has been fully integrated and this is not necessary anymore.
