### ISSUE TITLE
Remove context param from TracedClient.Do() and interface

### ISSUE THREAD

**Issue by j0hnsmith** [beatlabs/patron#378]
## Is your feature request related to a problem? Please describe
The first argument to the `Do()` method is a context, it doesn't need to be there.

https://github.com/beatlabs/patron/blob/828d471b287faab23c0e782dc0aebd7f5dc6916a/client/http/http.go#L78

## Is this a bug? Please provide steps to reproduce, a failing test etc.

Not a bug

## Describe the solution

The context can instead come from `req.Context()` (usage is minimal). This would make the signature the same as https://golang.org/pkg/net/http/#Client.Do, the benefit being greater compatibility with other code (eg wrapping or retry possibly). The interface would also need to be changed.

## Additional context

This would be a breaking change, the PR would be small but I'm not creating it at this time as I know patron tries to avoid breaking changes as much as possible. Creating this as something to come back to when other breaking changes are made (obviously if consensus says this is a good idea).

**Comment by mantzas** [comment]
@j0hnsmith  Makes a lot of sense. The reason why we added the context was to make it explicit. As you can see from code we are using it to propagate traces. How should we hange the situation when the request does not contain a context? Should we return an error or should we just go on without tracing? (I would be more inclined for the second but we have to make this aware somehow).

**Comment by j0hnsmith** [comment]
`req.Context()` defaults to a [background context when no other is provided](https://golang.org/src/net/http/request.go?s=12419:12462#L336). Putting the context that has the tracing info on the request is the right thing to do for cancellation purposes (and obviously tracing), it feels reasonable to put the onus it on the caller, the function doc (and release notes) would be the place to communicate to callers. 

Going on without tracing seems fair, on the other hand returning an error ensures that callers can't avoid it. Initially my instinct was continue without tracing but now I'm thinking returning an error is in the caller's interest (if they don't do it they should get failing tests when they update the patron version). I'm a believer in doing everything you can to avoid apis being misused.

**Comment by mantzas** [comment]
My main concern is that some people will like approach a vs b so it is tricky. Also if we return error we would be actually saying `hey you are using patron http client because you actually want tracing and you do not provide the context for it...`
Tough question: maybe @drakos74 or @tpaschalis can give their opinion?

**Comment by mantzas** [comment]
@j0hnsmith hey, we just discussed it with the rest and we are ok to move forward without returning an error if the context does not contain any trace Information.

**Comment by j0hnsmith** [comment]
Cool, should I make a PR or will we leave it until there are other breaking changes?

**Comment by mantzas** [comment]
@j0hnsmith You can proceed with the fix. We are still in v0 so breaking changes are expected, but we are close to v1.
