### ISSUE TITLE
Add optional timeout parameter to router builder

### ISSUE THREAD

**Issue by jeromeshapiro** [beatlabs/patron#391]
Patron is missing an equivalent to the std library HTTP [TimeoutHandler](https://golang.org/pkg/net/http/#TimeoutHandler). This handler is very useful as it sets a timeout on the amount of time a HTTP handler can execute, as well as a timeout on the `req.Context` passed into the handler, enabling not only the handler to fail gracefully once a given timeout has exceeded, but the resources which the handler has passed the context to as well.

**Scope**
Add an optional parameter in the HTTP route builder, allowing a timeout to be set for the handler and its associated context. If the timeout of the route has exceeds its limit before the handler has finished executing, the route will return a `503 Service Unavailable` and its associated context will be timed out, allowing each of the associated resources the context has been passed to to be gracefully shutdown.

This flow mimics the behaviour of the standard library's [TimeoutHandler](https://golang.org/pkg/net/http/#TimeoutHandler) feature.

**Comment by mantzas** [comment]
HTTP v2 PR has implemented it. Check it out at https://github.com/beatlabs/patron/pull/437
Closing this one.
