### ISSUE TITLE
Giving a way to async consumers to access original message headers

### ISSUE THREAD

**Issue by teivah** [beatlabs/patron#415]
## Is your feature request related to a problem? Please describe

If I'm not mistaken, there's no way yet in the `async.Message` interface to access the header of a message. We should in my opinion provide this option to the consumers as the concept of headers is probably generic enough to be included in `async.Message`.

For example, a consumer might want to filter messages giving a specific header.

## Is this a bug? Please provide steps to reproduce, a failing test etc.

N/A

## Describe the solution

Two possible options:
* Add a `Headers` method in `async.Message` that would return a list of headers.
* Another option could be to include all the headers within the Go context included in `async.Message`. It would mean iterating over each header and doing something like `context.WithValue(headerKey, headerValue)`.

The first option would make things more explicit but the second has the advantage of being less impacting as it doesn't require adding a method.

**Comment by mantzas** [comment]
@teivah We have deprecated the async components and we are using now the ones that are in the kafka package (instead the ones in the async one). There the sarama message is fully available. The only catch is that we have only implemented the group consumer and not the single one hoping that someone would tackle it at some point.

**Comment by teivah** [comment]
@mantzas Clear, thanks. Let's close it then.
