### ISSUE TITLE
Migrate from Jaeger/Opentrace to Open-telemetry clients/SDKs

### ISSUE THREAD

**Issue by rbroggi** [beatlabs/patron#434]
## Is your feature request related to a problem? Please describe

As in [this official communication](https://github.com/jaegertracing/jaeger/issues/3362) Jaeger clients and opentrace libraries deprecation have been announced for December. OpenTelemetry is the recommended alternative. I'm opening this issue so we can centralize discussions and efforts to make this migration in patron while minimizing side effects to users. 

## Describe the solution

We should replace the following dependencies (can be found in `go.mod`):

```
github.com/uber/jaeger-client-go
github.com/uber/jaeger-lib
github.com/opentracing/opentracing-go
```

in favor of:

```
go.opentelemetry.io/otel/sdk
go.opentelemetry.io/otel
go.opentelemetry.io/otel/trace
go.opentelemetry.io/otel/exporters/jaeger
go.opentelemetry.io/otel/exporters/prometheus
```

## Additional context

Useful links:

* [opentelemetry](https://opentelemetry.io/)
* [A migration from jaeger-client to open telemetry example](https://medium.com/jaegertracing/migrating-from-jaeger-client-to-opentelemetry-sdk-bd337d796759) (unfortunately in Java).
* [Jaeger client deprecation communication](https://github.com/jaegertracing/jaeger/issues/3362)

**Comment by mantzas** [comment]
@rbroggi We did wait for OpenTelemetry to become production grade in all (tracing, metric and logs) and make an overhaul.
Metrics are still alpha and logs seemed to be frozen. 
Will this be seamless of more like a breaking change?

**Comment by rbroggi** [comment]
> @rbroggi We did wait for OpenTelemetry to become production grade in all (tracing, metric and logs) and make an overhaul. Metrics are still alpha and logs seemed to be frozen. Will this be seamless of more like a breaking change?

I'm still in the early stage of evaluating the consequences for patron. I'm not sure if it will be a breaking change yet. 
Metrics are indeed still in alpha, and probably we should be considering to scope this issue to tracing only.

Whichever direction we choose to go, I think we can use this issue to keep track of our choices and collect inputs, opinions, and experiments to make an informed decision going forward. 

I don't think we need to rush, but the deprecation warning of jaeger-client (and the recommendation from the jaeger team to open telemetry) is something worth acknowledging.

**Comment by mantzas** [comment]
I did not see that at all!
That makes it a good candidate for moving to it!
Let's 🤞🏼 that nothing breaks.

**Comment by mantzas** [comment]
@rbroggi for completeness sake can you also add a link for the deprecation notice?

**Comment by rbroggi** [comment]
> add a link for the deprecation notice?

It is the first link above: `this official communication` in:
> As in this official communication Jaeger clients and opentrace libraries deprecation

**Comment by rbroggi** [comment]
As I'm trying to update the official set of examples in Jaeger, I will try to update patron as an experiment after that. 

We could consider releasing a beta patron version and use in some services for a while before massive adoption.

**Comment by mantzas** [comment]
The change is very deeply integrated in all component clients etc. It will be a bigger task i am afraid (assuming it will not be a seamless upgrade).
