### ISSUE TITLE
Abstraction on top of metrics to support exemplars without a need from an end user to provide suffices

### ISSUE THREAD

**Issue by EvgeniaMartynova-thebeat** [beatlabs/patron#463]
## Is your feature request related to a problem? Please describe

With [this PR](https://github.com/beatlabs/patron/pull/448) we introduced Prometheus Exemplars for `Histogram` and `Conuter` metrics in clients and components. 
However what we found out later exemplars are supported only for `Histogram` and `Counter` metrics with names ending with `_bucket` and `_total` suffices respectively. Not following the requirement is bringing a service monitor down. We partially reverted the exemplar support for those metrics which don't follow the naming standard in [this PR](https://github.com/beatlabs/patron/pull/460) and will address the issue with Prometheus. 
Meanwhile `Histogram` and `Counter` metric names used in `patron` have to adhere to [OpenMetrics standard](https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md) and have to have the above suffices. Please also refer to [this doc](https://prometheus.io/docs/practices/naming/) about metic name convention.

## Describe the solution

Here is a suggestion from @mantzas how to do it:

> If not would it make sense for us to provide our Counter and Histogram constructors so that we support exemplars without the end users needing to provide the names? Even our own abstractions to support exemplars in the first place so that the type assertions are hidden?
...
let's add this also to histogram for consistency.
We still need to create a patron histogram to expose methods for exemplar and non-exemplar usage.
This abstraction should be a thin as possible e.g. native embedding/composition strategy.

**Comment by mantzas** [comment]
Possibly also for Gauge.
