### ISSUE TITLE
We need to be able to setup a generic middleware stack

### ISSUE THREAD

**Issue by georgegg** [beatlabs/patron#47]
## Is your feature request related to a problem? Please describe

Framework has no generic middleware stack mechanism for default http component.
We want to be able to introduce middleware to routes such as CORS middleware etc.

## Is this a bug? Please provide steps to reproduce, a failing test etc.

This is not a bug but an enhancement.

## Describe the solution

We should be able to set in main service as an OptionFunc and then in the default http component as a slice of MiddlewareFunc, that are applied on all routes chained in order after the default middlewares of auth and tracing.

## Additional context

We can take this feature even further:
1. POST/PRE middleware
2. Per route middleware

**Comment by mantzas** [comment]
@cpapidas @sotirispl  This is the issue for the PR https://github.com/thebeatapp/patron/pull/46.
