### ISSUE TITLE
Redis client histograms use command + arguments in metric labels

### ISSUE THREAD

**Issue by siavashs** [beatlabs/patron#474]
## Is your feature request related to a problem? Please describe

The implementation of [`AfterProcess`](https://github.com/beatlabs/patron/blob/7d46f2a1598fceaf6c82fec2b2aea4db94d2f0d8/client/redis/redis.go#L72) hook uses the redis command name + args.
This results in `client_redis_cmd_duration_seconds_count` to have unlimited label values for the `command` label:
```
client_redis_cmd_duration_seconds_count{command="get key1"}
client_redis_cmd_duration_seconds_count{command="get key2"}
...
```

This could also be considered a security issues depending on the environment as the redis key names will leak into the metrics or can be fetched if `/metrics` endpoint of the application is exposed externally.

## Is this a bug? Please provide steps to reproduce, a failing test etc.

- Use Patron's redis client
- Collect the metrics using prometheus
- Run this PromQL query: `sum(client_redis_cmd_duration_seconds_count) by (command)`

## Describe the solution

Using the `name` without the `args` for the `command` label value will fix the issue.

## Additional context

A relevant issue has been discussed internally at Beat.

**Comment by siavashs** [comment]
Also note that we are using similar implementation for [tracing spans](https://github.com/beatlabs/patron/blob/7d46f2a1598fceaf6c82fec2b2aea4db94d2f0d8/client/redis/redis.go#L65) but I was not sure if we should change that in case there is a value in tracing queries to specific redis keys.
Let me know what you think.

**Comment by mantzas** [comment]
@siavashs nice catch! would you like to make the same change for tracing?

**Comment by siavashs** [comment]
@mantzas sure, I'll update the PR.
