### ISSUE TITLE
Deprecate all legacy client and components towards v1

### ISSUE THREAD

**Issue by mantzas** [beatlabs/patron#478]
## Is your feature request related to a problem? Please describe

For our v1 release we should only have only the latest clients and components.

## Describe the solution

- Delete all legacy client and components
- Move all remaining to the right place

**Comment by wishperera** [comment]
Can i take this task once https://github.com/beatlabs/patron/pull/581 is closed?

**Comment by mantzas** [comment]
Great. The only problem I see is since this is a breaking change and we have introduced multiple ones if we should follow the pattern of breaking one thing per release.
@wishperera @xenosdio @pkritiotis WDYT?

**Comment by wishperera** [comment]
I agree it is a safer approach.

**Comment by mantzas** [comment]
Would it make sense to list them all and add them as a bullet list and sub-tasks as we have done it [here](https://github.com/beatlabs/patron/issues/534)?

**Comment by xenosdio** [comment]
> Great. The only problem I see is since this is a breaking change and we have introduced multiple ones if we should follow the pattern of breaking one thing per release.
@wishperera @xenosdio @pkritiotis WDYT?

It is a safer approach, but what would be optimal? Each version introducing a breaking change, hence upgrading Patron would require updating the code, or all changes occurring in one single version? I would lean toward the latter.

**Comment by wishperera** [comment]
@xenosdio makes a good point , from a consumer's view point, multiple breaking changes in consecutive releases is a hassle.

**Comment by mantzas** [comment]
So we have either a big-bang breaking change that affects everybody or smaller changes that might affect some people (based on what they use). Example: not all use AWS so the breaking change blast radius is smaller.

With breaking changes per release we can provide simpler upgrade instructions. Big bang might be a mess...
I am not sure about which is the best, I tend to prefer the later in smaller steps.
