### ISSUE TITLE
Service Builder Pattern

### ISSUE THREAD

**Issue by mantzas** [beatlabs/patron#48]
## Is your feature request related to a problem? Please describe

The patron service is a very complex struct and is build at this point by injecting dependencies.
We could use the builder pattern to make the API much more simple, user friendly and intuitive.

## Describe the solution

We could have something like the following:

```go
s,err:=NewBuilder().WithKafkaConsumer(...).WithAmqpConsumer(...).WithRoutes(...).Build()
```

## Additional context

Given the above we could clean up the service, options and others e.g. routes, middlewares might not need to be a field of the service struct.

**Comment by aziule** [comment]
The idea is great, and I think we should not forget to allow developers to build Patron using their own, custom components (e.g.: `MyCustomConsumer`).

It _could_ be implemented with a more generic method, such as:

```go
s, err := NewBuilder().WithComponent(MyCustomConsumer).Build()
```

**Comment by tpaschalis** [comment]
I've begun work for this, so we can start closing issues towards v1.0.0
