### ISSUE TITLE
HTTP custom encoding headers and encoders/decoders 

### ISSUE THREAD

**Issue by mantzas** [beatlabs/patron#5]
## Is your feature request related to a problem? Please describe

We need a option to allow for custom header for decode/encode payload over HTTP.

## Describe the solution

- HTTP component has to accept a new Encoding option.
- The new functions have to be added to the currently supported ones, or overwrite them

**Comment by tpaschalis** [comment]
Are we thinking something like custom `Content-Encoding` and `Transfer-Encoding` headers, as well as the connection to our `encoding` package to be used by the default handler?

I could take this for a spin, but a more concrete example of what we're aiming for would be great!

**Comment by mantzas** [comment]
@tpaschalis 
The idea here was to be able to provide content-type/accept-header and provide specific encode/decoders.
e.g. `application/xml` for content-type and accept-header and providing xml encode and decoders...
With this approach somebody could support everything and we dont need to use the raw http stuff and do all by hand...
Currently we support JSON and Protobuf...
Makes sense?

**Comment by mantzas** [comment]
Since we moved to HTTP v2 handling of requests is now left to the developer. Closing
