### ISSUE TITLE
RabbitMQ consumer enhancements 

### ISSUE THREAD

**Issue by harry-pap** [beatlabs/patron#51]
Currently the RabbitMQ consumer(async/amqp/amqp.go) uses hardcoded configuration for the exchange/queue/bindings .

This is problematic both when patron runs on a clean Rabbit installation(as the client should provide the desired configuration), but also when the Rabbit instance has been configured, as the client will fail if a queue or exchange with a given name already exists, but has different configuration(for example if the exchange type[direct, fanout, etc] is different)

We need to update amqp, to allow the clients provide the configuration

**Comment by mantzas** [comment]
@chpapadop you are correct, i assumed that every exchange might be a fanout one (which might be the case in a lot of scenarios).
Which are the properties that we need to address here? Exchange Type?

**Comment by harry-pap** [comment]
@mantzas Exchange type and bindings should be enough, after re-examination I don't think different configuration for the queues will ever be needed
