### ISSUE TITLE
Route Builder Pattern

### ISSUE THREAD

**Issue by mantzas** [beatlabs/patron#52]
## Is your feature request related to a problem? Please describe

Route have a lot of configuration and could be a good candidate for the builder pattern.

## Describe the solution

We could support creating a route with following options:

- Raw using std handler
- Using patron handler
- Using trace
- Using auth
- etc.

```go
New("GET", "/user").WithStdHandler(hnd).Create()
```
or
```go
New("GET", "/user").WithHandler(hnd).WithAuth(auth).WithTrace(cfg).Create()
```

**Comment by gkech** [comment]
I will start with this one

**Comment by mantzas** [comment]
@gkech Hi, this has been here here for a long time and we want to move to milestone v1.0. I am almost finished with the implementation. Thanks
