### ISSUE TITLE
HTTP Component builder pattern

### ISSUE THREAD

**Issue by mantzas** [beatlabs/patron#53]
## Is your feature request related to a problem? Please describe

The HTTP component needs a lot of configuring in order to be setup which makes it a good candidate for the builder pattern.
Some of the options are:
- Timeouts
- SSL
- Routes
- Middlewares
- etc.

## Describe the solution

Ideally we should have the std builder pattern which could look like:

```go
cmp,err:= http.New().WithSSL(cert,key).WithRoutes(rr).WithMiddleWares().Create()
```

**Comment by tpaschalis** [comment]
Is this still up for grabs? I could take a stab at it.
