### ISSUE TITLE
Async Component Builder Pattern

### ISSUE THREAD

**Issue by mantzas** [beatlabs/patron#54]
## Is your feature request related to a problem? Please describe

The async component needs a lot of configuring in order to be setup which makes it a good candidate for the builder pattern.
Some of the options are:
- Consumer
- Failure strategy
- Retries
- etc.

## Describe the solution

Ideally we should have the std builder pattern which could look like:

```go
cmp,err:= async.New(consumer).WithFailureStrategy(strg).WithRetries(cfg).Create()
```

**Comment by drakos74** [comment]
i ll pick this one up, if noone else has already started working on it !
