### ISSUE TITLE
Split up Kafka consumers

### ISSUE THREAD

**Issue by mantzas** [beatlabs/patron#70]
## Is your feature request related to a problem? Please describe

In order to support the consumer features better, we should split up the consumer types (consumer group and simple).
This will enable us to create the consumer group with support for multiple topics.

## Describe the solution

The package structure should be the following:

- kafka
  - group (support for consumer groups)
  - simple (no consumer groups)

where kafka root contains all the common code and group and simple only the one required for consumer type.

**Comment by moukoublen** [comment]
I'd like to pick this up :relaxed:
