### ISSUE TITLE
Make the kafka producer retry policy configurable

### ISSUE THREAD

**Issue by harry-pap** [beatlabs/patron#75]
## Describe the solution

Add an OptionFunc in the kafka package, which will set the number of retries and the sleep interval of the sarama producer

**Comment by mantzas** [comment]
Pls provide the full description based on the GitHub template, so we can understand what the problem exactly is you are trying to solve.

**Comment by harry-pap** [comment]
This issue is redundant, the functionality described is already in place in the ConsumerRetry OptionFunc
