### ISSUE TITLE
Enhance example documentation

### ISSUE THREAD

**Issue by mantzas** [beatlabs/patron#84]
## Is your feature request related to a problem? Please describe

We should have more information on what each service does.

## Describe the solution

Add information to the examples readme file.

**Comment by superstas** [comment]
Hey @mantzas, I'd like to take ownership of it, if you don't mind.  
I've got a couple of questions.

- Are there any major updates for this issue given that it's created in Sep 2019 ( many things might have changed )?
- Does this issue somehow relate to #150?
- Do we need to add/update extra examples?


Thank you.

**Comment by mantzas** [comment]
@superstas Hey.
This ticket is about enhancing documentation only the examples of Patron. Not the whole project.
We will eventually build better documentation after #150 .

**Comment by mantzas** [comment]
We have overhauled all our documentation, so we can close this issue.
