### ISSUE TITLE
Default health check implementation

### ISSUE THREAD

**Issue by azarakovskiy** [beatlabs/patron#91]
## Is your feature request related to a problem? Please describe

There is a route in Patron to handle health check but there is no implementation of a composite health check worker that will monitor multiple health checks at once. 

## Describe the solution

Composite health check accepts N functions, each reporting about the health status of some particular part of the system. If any of them start to fail, the composite also fails the health check.

This composite checker provides a single function that is fed to Patron for a default http healthcheck endpoint.

## Additional context

The idea of how it could be done is here: https://github.com/taxibeat/canary-service/tree/master/internal/health
https://github.com/taxibeat/canary-service/blob/master/internal/health/health.go#L71

I'd only migrate timer-based implementation to channel-based so that functions can recover if needed, and the decision whether to crash a service will be delegated to a client.

**Comment by mantzas** [comment]
There is already something in the backlog which would support kubernetes liveness and readiness... https://github.com/beatlabs/patron/issues/28
