### ISSUE TITLE
Introduce /health and /metrics sync_http_requests prometheus metrics

### ISSUE THREAD

**Issue by oss92** [beatlabs/patron#92]
## Is your feature request related to a problem? Please describe

All HTTP routes are measured have prometheus metrics except /health and /metrics and they too are technically HTTP routes

## Is this a bug? Please provide steps to reproduce, a failing test etc.

Not a bug

## Describe the solution

Monitor the `/health` and `/metrics` routes the same way Patron tracks other routes

**Comment by mantzas** [comment]
Hi @oss92. This is actually on purpose since metrics on those routes don't give any valuable information.

**Comment by oss92** [comment]
@mantzas thought it might be useful for some of our services that don't have any HTTP endpoints except /health and /metrics and thus check the overall health of its limited HTTP interface.

Maybe that can be implemented as needed per service. Thanks for your timely response.
