### ISSUE TITLE
Add multiple []Route slices and assure non-duplication

### ISSUE THREAD

**Issue by azarakovskiy** [beatlabs/patron#97]
## Is your feature request related to a problem? Please describe

One of the ways to design routes in your app is to declare URL mappings in routes themselves, and then pass all of them to Patron.

So it looks something like this (pseudocode):
```
catHTTP := NewCatHTTP()
dogHTTP := NewDogHTTP()

var catRoutes, dogRoutes []http.Route
catRoutes = catHTTP.Routes()
dogRoutes = catHTTP.Routes()

patron.New( ... patron.Routes(
   combineRoutes(catRoutes, dogRoutes)
) ... )

...

func combineRoutes(rrs ...[]http.Route) ([]http.Route, error) { ... }
```

The proposal is to implement this method in Patron.

## Describe the solution

https://github.com/taxibeat/pricing-surge-service/pull/12/files#diff-d6344a9314798b136af53b3c99e586b9R60

**Comment by mantzas** [comment]
@azarakovskiy Hi, AFAIK if you give patron routes that are the same it will return an error (due to the underlying router). If it is not the case then we have a bug. Can you confirm that it works that way?

**Comment by azarakovskiy** [comment]
@mantzas you're right, patron fails when it finds a duplicate. Removed this part from the description.

**Comment by mantzas** [comment]
@azarakovskiy should we close this issue?

**Comment by azarakovskiy** [comment]
@mantzas can I instead suggest changing Patron's method signature from `func Routes(rr []http.Route) OptionFunc` to `func Routes(rr... []http.Route) OptionFunc`? This might be very useful to avoid combining multiple slices of routes on a client-side, and is yet backward compatible with anything existing.

**Comment by mantzas** [comment]
@azarakovskiy yes we could. There are 2 problems:
- variadic arguments allow to not pass anything in, but this is handled inside with a check
- this is a breaking change
I have no problem with this: 
- You have to update examples, tests, possible documentation etc.

Let's get an opinion from the other curators also. @cpapidas @sotirispl do you agree???
