### ISSUE TITLE
Add doc about the new alive and ready routes

### ISSUE THREAD

**Issue by aziule** [beatlabs/patron#98]
## Is your feature request related to a problem? Please describe

The doc does not tell what are the routes for the default endpoints created by Patron (readiness, liveness, ...). We have to dive into the code to find the routes (/alive, /ready, ...)

## Describe the solution

Add some doc to README.md:

* Routes to the different endpoints
* Status codes returned and their meaning

**Comment by mantzas** [comment]
@aziule there is a mention in the readme. Would you like a special section to make that clearer?

**Comment by aziule** [comment]
It is mentioned that there are a live and ready endpoint, but the routes themselves (`/alive` and `/ready`) are not documented.

I think it would be nice to have them specifically written.

**Comment by mantzas** [comment]
I agree, r u up for it?

**Comment by aziule** [comment]
Yep
